"""Fusionando UsuarioConfiguracion y PlantillaPersonalizada

Revision ID: 59b8d73fc637
Revises: be390f10d6c9
Create Date: 2025-05-08 22:27:03.872224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b8d73fc637'
down_revision = 'be390f10d6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puntaje_promedio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comentarios_general', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.drop_column('comentarios_general')
        batch_op.drop_column('puntaje_promedio')

    # ### end Alembic commands ###
