"""se agrega columna html generado

Revision ID: 640c5b4d4397
Revises: 59b8d73fc637
Create Date: 2025-05-09 12:41:13.582611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640c5b4d4397'
down_revision = '59b8d73fc637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido_editado', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.drop_column('contenido_editado')

    # ### end Alembic commands ###
