"""Añadir plantilla_personalizada

Revision ID: 9026e891f91e
Revises: 42c9935dd011
Create Date: 2025-05-08 12:14:07.759547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9026e891f91e'
down_revision = '42c9935dd011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantilla_personalizada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_plantilla', sa.String(length=100), nullable=False),
    sa.Column('datos_json', sa.JSON(), nullable=False),
    sa.Column('imagenes', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.Column('url_preview', sa.String(length=255), nullable=False),
    sa.Column('url_final', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_final'),
    sa.UniqueConstraint('url_preview')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('ciudad_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('ciudad_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('plantilla_personalizada')
    # ### end Alembic commands ###
