"""se agrega columna html generado

Revision ID: a155fec2a46b
Revises: 640c5b4d4397
Create Date: 2025-05-09 14:23:16.349538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a155fec2a46b'
down_revision = '640c5b4d4397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('birthday_day', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('birthday_month', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('birthday_year', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('courses', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('facebook_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('other_social_media', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('products_heading', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('products_see_more_text', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('about_you_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_1_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_1_short_phrase', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_1_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_2_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_2_short_phrase', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_2_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_3_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_3_short_phrase', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portfolio_service_3_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('additional_portfolio_service', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('html_generado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('service_rating_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'service_ratings', ['service_rating_id'], ['id_rating'])
        batch_op.drop_column('author')

    with op.batch_alter_table('service_ratings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plantilla_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'plantilla_personalizada', ['plantilla_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_ratings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('plantilla_id')

    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_rating_id')
        batch_op.drop_column('html_generado')
        batch_op.drop_column('additional_portfolio_service')
        batch_op.drop_column('portfolio_service_3_description')
        batch_op.drop_column('portfolio_service_3_short_phrase')
        batch_op.drop_column('portfolio_service_3_name')
        batch_op.drop_column('portfolio_service_2_description')
        batch_op.drop_column('portfolio_service_2_short_phrase')
        batch_op.drop_column('portfolio_service_2_name')
        batch_op.drop_column('portfolio_service_1_description')
        batch_op.drop_column('portfolio_service_1_short_phrase')
        batch_op.drop_column('portfolio_service_1_name')
        batch_op.drop_column('about_you_description')
        batch_op.drop_column('products_see_more_text')
        batch_op.drop_column('products_heading')
        batch_op.drop_column('other_social_media')
        batch_op.drop_column('instagram_link')
        batch_op.drop_column('facebook_link')
        batch_op.drop_column('business_description')
        batch_op.drop_column('courses')
        batch_op.drop_column('address')
        batch_op.drop_column('birthday_year')
        batch_op.drop_column('birthday_month')
        batch_op.drop_column('birthday_day')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
