"""Fusionando UsuarioConfiguracion y PlantillaPersonalizada

Revision ID: be390f10d6c9
Revises: 9026e891f91e
Create Date: 2025-05-08 22:14:05.050802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be390f10d6c9'
down_revision = '9026e891f91e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('author', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('home_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('about_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('product_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hero_title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('hero_subtitle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contact_us_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('about_heading', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('about_description_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_description_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('read_more_text', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('have_color_palette', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('suggest_color_palette', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('color_palette_choice', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('domain_agreement', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('referrals', sa.Integer(), nullable=True))
        batch_op.drop_column('datos_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datos_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_column('referrals')
        batch_op.drop_column('domain_agreement')
        batch_op.drop_column('feedback')
        batch_op.drop_column('color_palette_choice')
        batch_op.drop_column('suggest_color_palette')
        batch_op.drop_column('have_color_palette')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('read_more_text')
        batch_op.drop_column('about_description_2')
        batch_op.drop_column('about_description_1')
        batch_op.drop_column('about_heading')
        batch_op.drop_column('contact_us_text')
        batch_op.drop_column('hero_subtitle')
        batch_op.drop_column('hero_title')
        batch_op.drop_column('contact_url')
        batch_op.drop_column('client_url')
        batch_op.drop_column('product_url')
        batch_op.drop_column('about_url')
        batch_op.drop_column('home_url')
        batch_op.drop_column('company_name')
        batch_op.drop_column('title')
        batch_op.drop_column('author')
        batch_op.drop_column('description')
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
