"""se agrega columna html generado

Revision ID: d925072c506a
Revises: a155fec2a46b
Create Date: 2025-05-09 14:40:00.439742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd925072c506a'
down_revision = 'a155fec2a46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.drop_constraint('plantilla_personalizada_service_rating_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_rating_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantilla_personalizada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_rating_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('plantilla_personalizada_service_rating_id_fkey', 'service_ratings', ['service_rating_id'], ['id_rating'])

    # ### end Alembic commands ###
