[database]
host = ep-crimson-hill-ahi5k3jd-pooler.c-3.us-east-1.aws.neon.tech
user = neondb_owner
password = npg_uRcS1h6sUTXA
database = neondb
port = 5432
url = postgresql://neondb_owner:npg_uRcS1h6sUTXA@ep-crimson-hill-ahi5k3jd-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require